"""empty message

Revision ID: c7e35f71b90a
Revises: f44369120cf7
Create Date: 2020-02-18 16:34:29.579586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e35f71b90a'
down_revision = 'f44369120cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hierarchy', sa.Column('hierarchy_node_type_id', sa.Integer(), nullable=False))
    op.add_column('hierarchy', sa.Column('predecessor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hierarchy', 'hierarchy_node_type', ['hierarchy_node_type_id'], ['id'])
    op.create_foreign_key(None, 'hierarchy', 'hierarchy', ['predecessor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hierarchy', type_='foreignkey')
    op.drop_constraint(None, 'hierarchy', type_='foreignkey')
    op.drop_column('hierarchy', 'predecessor_id')
    op.drop_column('hierarchy', 'hierarchy_node_type_id')
    # ### end Alembic commands ###
